function V = myODE(t,Y)
%myODE
%    V = myODE(T,Y)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-Feb-2025 19:55:06

t2 = Y(2);
V = [t2;t2.*(-1.0./2.0)-Y(1).*2.0];
end
